{% set name = "suds" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/suds-{{ version }}.tar.gz
  sha256: 83b162c3d2355374e11d8b9acf15eeaa158b416b4625821844f9f628d679deaf

build:
  noarch: python
  # Default package name is suds-community and needs to be overridden with an environment variable
  # https://github.com/suds-community/suds/blob/a616d96b070ca119a532ff395d4a2a2ba42b257c/setup.py#L648
  # This will change in in the 2.0.0 release
  # https://github.com/suds-community/suds/blob/a616d96b070ca119a532ff395d4a2a2ba42b257c/README.md#overview
  script: SUDS_PACKAGE=suds {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - suds
    - suds.bindings
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/suds-community/suds
  summary: Lightweight SOAP client (community fork)
  license: LGPL-3.0-only
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - chrisburr
